service: photo-bus

plugins:
  - serverless-plugin-typescript

useDotenv: true
provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x
  region: ap-southeast-2
  timeout: 900
  memorySize: 1024
  environment:
    NODE_ENV: ${env:NODE_ENV, "development"}
    ACCOUNT_EMAIL: ${env:ACCOUNT_EMAIL}
    ACCOUNT_PASSWORD: ${env:ACCOUNT_PASSWORD}

functions:
  hello:
    handler: handler.hello
  upload:
    handler: handler.upload
