service: photo-bus

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x
  region: ap-southeast-2
  timeout: 900
  memorySize: 1024
  environment:
    NODE_ENV: production

functions:
  hello:
    handler: handler.hello
  upload:
    handler: handler.upload
