service: photo-bus

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x
  region: ap-southeast-2
  timeout: 900

functions:
  hello:
    handler: app/handler.hello
  upload:
    handler: app/handler.upload
    layers:
      # Layer for chrome-aws-lambda: https://github.com/shelfio/chrome-aws-lambda-layer
      - "arn:aws:lambda:ap-southeast-2:764866452798:layer:chrome-aws-lambda:31"
