name: build

on: push

jobs:
  build:
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Lint
        if: ${{ always() }}
        run: npm run lint
      - name: Check types
        if: ${{ always() }}
        run: npm run typecheck
      - name: Run unit tests
        if: ${{ always() }}
        run: npm run test
      - name: Configure AWS credentials
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
          ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
          NODE_ENV: production
        run: npm run deploy
